// netlify/functions/raven.js
// This file goes in: netlify/functions/raven.js

exports.handler = async (event, context) => {
  const ravenFinds = [
    "a soda can tab",
    "a paperclip",
    "a gum wrapper",
    "a key with no lock",
    "a lost button",
    "a bottle cap",
    "a bent spoon",
    "a marble",
    "a tiny bell",
    "a coin from 1987",
    "a bead from a broken necklace",
    "a crumpled foil ball",
    "a safety pin",
    "a zipper pull",
    "a thimble",
    "a watch face with no hands",
    "a nail",
    "a washer",
    "a piece of tinfoil shaped like a ravenn",
    "a battery (do not eat)",
    "a tiny gear from an unknown machine",
    "a rusted screw",
    "a sequin",
    "a single earring",
    "a cufflink",
    "a tiny magnifying glass",
    "a cracked compact mirror",
    "a dog tag with no name",
    "a drawer handle",
    "a bolt",
    "a guitar pick",
    "a coin with a hole in it",
    "a fragment of stained glass",
    "a glittery button",
    "a fishing lure",
    "a bottle of glitter",
    "a nail polish cap",
    "a toy ring",
    "a stray chess piece",
    "a pocket watch",
    "a watch battery",
    "a crystal bead",
    "a foil candy wrapper",
    "a screw-top lid",
    "a shard of polished shell",
    "a lighter",
    "a shiny washer from a skateboard",
    "a chandelier crystal",
    "a small brass key",
    "a coin from an arcade",
    "a polished stone",
    "a loose gem from costume jewelry",
    "a decorative tack",
    "a soda bottle lid",
    "a teaspoon",
    "a lock of hair tied with ribbon (slightly cursed)",
    "a phone SIM card",
    "a holographic sticker",
    "a bent fork",
    "a shiny button from a coat",
    "a charm from a charm bracelet",
    "a bolt from a park bench",
    "a ring pull from an old can",
    "a pen cap",
    "a tiny screwdriver",
    "a glow-in-the-dark star",
    "a reflective road reflector",
    "a metal whistle",
    "a gear from a clock",
    "a spark plug",
    "a coin from a foreign country",
    "a hair clip",
    "a pin badge",
    "a small trophy plate",
    "a pendant from a necklace",
    "a shiny screw-on earring back",
    "a glittery pen",
    "a brass button",
    "a gaming token",
    "a tiny silver spoon",
    "a fishing swivel",
    "a washer chain",
    "a rivet",
    "a small metal dice",
    "a lapel pin",
    "a shiny shell casing (empty)",
    "a compact mirror",
    "a brooch",
    "a bolt from a bike",
    "a decorative keychain charm",
    "a bead shaped like a star",
    "a shiny metal bookmark",
    "a decorative button from upholstery",
    "a glass marble with glitter inside",
    "a small tin",
    "a fake gold coin",
    "a dog collar tag",
    "a piece of glitter tape",
    "a sequin-covered patch",
    "a tangle of metallic thread",
    "a diamond earring (just one)",
    "a gold wedding band",
    "a silver pocket watch",
    "a pearl necklace clasp",
    "a sapphire brooch",
    "a platinum cufflink",
    "a gold coin from 1824",
    "a ruby tie pin",
    "an emerald pendant",
    "a designer watch (slightly pecked)",
    "a vintage locket with a secret photo",
    "a silver ingot the size of a matchbox",
    "a rare coin in a display case",
    "a crystal paperweight",
    "an antique fountain pen",
    "a miniature fabergé egg",
    "a jeweled hair comb",
    "a diamond tennis bracelet",
    "a gemstone-studded belt buckle",
    "a vintage camera lens",
    "a gold-plated lighter",
    "a hand-engraved silver flask",
    "a pocketknife with an opal handle",
    "a rare postage stamp in a plastic sleeve",
    "a platinum chain necklace"
  ];

  // Get random item
  const item = ravenFinds[Math.floor(Math.random() * ravenFinds.length)];
  
  // Build message
  const message = `⋆˚✦ you've befriended a raven. as a sign of affection, they have brought you ${item}.`;

  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'text/plain',
    },
    body: message
  };
};
